# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eesti andmeteadus
description: > # this means to ignore newlines until "baseurl:"
  Eesti andmeteaduse ressursid: kommuunid, blogid, õppematerjalid, ettevõtted.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://datasci.ee" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  datasciee
facebook_link:    https://www.facebook.com/groups/datasciee
google_analytics: UA-37828611-8

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  posts:
    output: true
    permalink: /post/:year/:month/:day/:title/
  projects:

minima:
  date_format: "%d.%m.%Y"